Leaderboard April 3 release
ShishirPatil/gorilla pull request #309
Opened 2024-04-04 08:01 UTC by HuanzhiMao

This PR is for the leaderboard April 3 release:

1. Bug fix for evaluation dataset possible answers, including those that are identified in #301. 
2. Implement **string standardization** for the AST evaluation pipeline, i.e. removing white spaces and a subset of punctuations (`,./-_*^`) to make the AST evaluation more robust and accurate. 
3. Fix AST evaluation issue for type `tuple`. 
4. Add 2 new models `meetkai/functionary-small-v2.4 (FC)`, `meetkai/functionary-medium-v2.4 (FC)` to the leaderboard.

This PR **DOES** change the leaderboard score. We will update the leaderboard shortly, in a different PR. 

---------

Co-authored-by: Charlie Cheng-Jie Ji <charliechengjieji@berkeley.edu>
Co-authored-by: Fanjia Yan <fanjiayan@berkeley.edu>

2024-04-04 08:12 UTC, ShishirPatil requested changes

2024-04-04 08:19 UTC, HuanzhiMao commented on berkeley-function-call-leaderboard/README.md
>  * [#299](https://github.com/ShishirPatil/gorilla/pull/299) Leaderboard April 1 update with new models (`Claude-3-Haiku`, `Databrick-DBRX-Instruct`), more advanced AST evaluation procedure, and update
removed

2024-04-05 04:02 UTC, CharlieJCJ approved these changes
LGTM

2024-04-05 07:36 UTC, ShishirPatil approved these changes

2024-04-05 07:36 UTC, merged