[BFCL] Fix Dataset and Possible Answer Issue
ShishirPatil/gorilla pull request #557
Opened 2024-07-26 02:22 UTC by HuanzhiMao

This PR fixes #550.
Thanks @lucenzhong !

Here's a breakdown of the changes:
- parallel function category: 1 entry affected.
  - Indices: `89`

This will affect the leaderboard score. We will update it soon, in a different PR.

2024-08-01 07:00 UTC, XuHwang commented
Hi, thanks for your efforts in supporting such a wonderful benchmark.

Recently I found some possible errors in ground truth as follows:

1. id 278 in simple.json: `features` is not required and default value `price` is right, while the ground truth requires it
2. id 285 in simple.json: `location` requires the format ` In the format City, State`, while the ground truth contains `Chicago` but does not contain `Chicago, Illinois`
3. id 375 in simple.json:  maybe the ground truth of `items` should include  `[pumpkin, dozen eggs]`

2024-08-01 07:02 UTC, HuanzhiMao commented
> Hi, thanks for your efforts in supporting such a wonderful benchmark.
> 
> Recently I found some possible errors in ground truth as follows:
> 
> 1. id 278 in simple.json: `features` is not required and default value `price` is right, while the ground truth requires it
> 2. id 285 in simple.json: `location` requires the format ` In the format City, State`, while the ground truth contains `Chicago` but does not contain `Chicago, Illinois`
> 3. id 375 in simple.json:  maybe the ground truth of `items` should include  `[pumpkin, dozen eggs]`

Thanks for pointing this out!

2024-08-01 08:17 UTC, XuHwang commented
> > Hi, thanks for your efforts in supporting such a wonderful benchmark.
> > Recently I found some possible errors in ground truth as follows:
> > 
> > 1. id 278 in simple.json: `features` is not required and default value `price` is right, while the ground truth requires it
> > 2. id 285 in simple.json: `location` requires the format ` In the format City, State`, while the ground truth contains `Chicago` but does not contain `Chicago, Illinois`
> > 3. id 375 in simple.json:  maybe the ground truth of `items` should include  `[pumpkin, dozen eggs]`
> 
> Thanks for pointing this out!
> 
> Regarding `simple_278`, the ground truth is correct. The question asks for `Find me the average price and ratings of piano from Yamaha.` while the default value for `features` only contain `'price'`, but not `'rating'`, so the model output must explicitly set it.
> 
> ```
> "features": {
>     "type": "array",
>     "items": {"type": "string", "enum": ["price", "rating"]},
>     "description": "The features to retrieve about the instrument. Default is 'price'",
> }
> ```

I see. I agree~
Thanks a lot!

2024-08-02 01:23 UTC, XuHwang commented
Hey, I found some possible errors of ground truth about the `lambda` function in python.

In `gorilla_openfunctions_v1_test_simple.json`: 
```json
{"id": "simple_13", "ground_truth": {"calculate_area_under_curve": {"function": ["x^2", "x**2"], "interval": [[1.0, 3.0]], "method": ["", "trapezoidal"]}}}
{"id": "simple_14", "ground_truth": {"calculate_derivative": {"function": ["3x^2 + 2x - 1", "3*x**2+2*x-1"], "x_value": ["", 0.0]}}}
{"id": "simple_15", "ground_truth": {"integrate": {"function": ["x^3", "x**3"], "start_x": [-2], "end_x": [3], "method": ["simpson"]}}}
{"id": "simple_16", "ground_truth": {"calculus.derivative": {"function": ["2*x^2", "2x^2", "2**x^2"], "value": [1], "function_variable": ["x", ""]}}}
```

While in `gorilla_openfunctions_v1_test_parallel_multiple_function.json`:
```json
{"id": "parallel_multiple_function_4", "ground_truth": {"integral": {"function": ["x^2", "lambda x : x**2"], "a": [1.0], "b": [5.0]}, "derivative": {"function": ["x^2", "lambda x : x**2"], "x": [3.0]}}}
```

I think maybe the lambda function should be included in the simple cases as well?

2024-08-02 04:29 UTC, HuanzhiMao commented
> Hey, I found some possible errors of ground truth about the `lambda` function in python.
> 
> In `gorilla_openfunctions_v1_test_simple.json`:
> 
> ```json
> {"id": "simple_13", "ground_truth": {"calculate_area_under_curve": {"function": ["x^2", "x**2"], "interval": [[1.0, 3.0]], "method": ["", "trapezoidal"]}}}
> {"id": "simple_14", "ground_truth": {"calculate_derivative": {"function": ["3x^2 + 2x - 1", "3*x**2+2*x-1"], "x_value": ["", 0.0]}}}
> {"id": "simple_15", "ground_truth": {"integrate": {"function": ["x^3", "x**3"], "start_x": [-2], "end_x": [3], "method": ["simpson"]}}}
> {"id": "simple_16", "ground_truth": {"calculus.derivative": {"function": ["2*x^2", "2x^2", "2**x^2"], "value": [1], "function_variable": ["x", ""]}}}
> ```
> 
> While in `gorilla_openfunctions_v1_test_parallel_multiple_function.json`:
> 
> ```json
> {"id": "parallel_multiple_function_4", "ground_truth": {"integral": {"function": ["x^2", "lambda x : x**2"], "a": [1.0], "b": [5.0]}, "derivative": {"function": ["x^2", "lambda x : x**2"], "x": [3.0]}}}
> ```
> 
> I think maybe the lambda function should be included in the simple cases as well?

Fair point. Updated.

2024-08-04 23:42 UTC, CharlieJCJ requested changes

2024-08-04 23:42 UTC, CharlieJCJ commented on berkeley-function-call-leaderboard/data/possible_answer/gorilla_openfunctions_v1_test_simple.json
Should be `lambda x: x**2`, need fix for all lambda functions.

`lambda x: x^2` is doing bitwise xor operation, no exponentiation.

2024-08-04 23:43 UTC, HuanzhiMao commented on berkeley-function-call-leaderboard/data/possible_answer/gorilla_openfunctions_v1_test_simple.json
Good catch.

2024-08-05 00:15 UTC, HuanzhiMao commented on berkeley-function-call-leaderboard/data/possible_answer/gorilla_openfunctions_v1_test_simple.json
addressed

2024-08-05 01:52 UTC, CharlieJCJ approved these changes
LGTM

2024-08-05 02:05 UTC, ShishirPatil approved these changes

2024-08-05 02:06 UTC, merged