[BFCL] Bug Fix parse_nested_value function for model_handler utils
ShishirPatil/gorilla pull request #660
Opened 2024-09-24 19:39 UTC by VishnuSuresh27

In the parse_nested_value function, added a check to determine whether we are dealing with another function call or if its a regular dictionary. Previous version of the code incorrectly assumed that this was function call and did not consider the case where the function argument is a dictionary. 

Fix https://github.com/ShishirPatil/gorilla/issues/652

2024-09-24 20:38 UTC, HuanzhiMao requested changes
Failed on the following test:
```
x = "[foo(a=1, b={'a': 1, 'b': 'hello'}), bar(c=3, d={'a': 1, 'b': foo(c=1, d=2)}), baz(e=f(x=1, y=2))]"

print(default_decode_execute_prompting(x))

# Expect ["foo(a=1, b={'a': 1, 'b': 'hello'})", 'bar(c=3, d={'a': 1, 'b': foo(c=1, d=2)})', 'baz(e=f(x=1, y=2))']
# But got ["foo(a=1, b={a=1, b='hello'})", 'bar(c=3, d={a=1, b=foo(c=1, d=2)})', 'baz(e=f(x=1, y=2))']
```

2024-09-24 21:15 UTC, VishnuSuresh27 commented
@HuanzhiMao Thank you for catching. Should be fixed in the latest commit.

2024-09-24 21:29 UTC, HuanzhiMao approved these changes
LGTM. Thanks @VishnuSuresh27

2024-09-25 03:26 UTC, ShishirPatil approved these changes

2024-09-25 03:26 UTC, merged